apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
  namespace: secrets-probes
spec:
  containers:
  - name: app
    image: mysql:8.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: username
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password
    - name: MYSQL_DATABASE
      value: "testdb"
    ports:
    - containerPort: 3306
