apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
  namespace: secrets-probes
spec:
  containers:
  - name: app
    image: nginx:alpine
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
    - name: tls-volume
      mountPath: /etc/tls
      readOnly: true
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Secret files:'; ls -la /etc/secrets /etc/tls; sleep 60; done"]
  volumes:
  - name: secret-volume
    secret:
      secretName: db-credentials
      defaultMode: 0400
  - name: tls-volume
    secret:
      secretName: tls-secret
  restartPolicy: Never
