apiVersion: v1
kind: ConfigMap
metadata:
  name: flyway-migrations
  namespace: storage-rds
data:
  V1__initial_schema.sql: |
    CREATE TABLE IF NOT EXISTS products (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(200) NOT NULL,
        description TEXT,
        price DECIMAL(10,2) NOT NULL,
        stock INT DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );
  V2__add_categories.sql: |
    CREATE TABLE IF NOT EXISTS categories (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL UNIQUE,
        description TEXT
    );
    ALTER TABLE products ADD COLUMN category_id INT;
    ALTER TABLE products ADD FOREIGN KEY (category_id) REFERENCES categories(id);
  V3__seed_data.sql: |
    INSERT IGNORE INTO categories (name, description) VALUES
    ('Electronics', 'Electronic devices and accessories'),
    ('Clothing', 'Apparel and fashion items'),
    ('Books', 'Books and publications');
    
    INSERT IGNORE INTO products (name, description, price, stock, category_id) VALUES
    ('Laptop', 'High-performance laptop', 999.99, 50, 1),
    ('T-Shirt', 'Cotton t-shirt', 19.99, 200, 2),
    ('Novel', 'Bestselling novel', 14.99, 100, 3);
