# ArgoCD Application for Mario Game
# Created by: Imran Shaikh

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mario-game
  namespace: argocd
spec:
  project: default
  
  # Source: Mario game Git repository
  source:
    repoURL: https://github.com/asecurityguru/gitops-pipeline-supermario-repo.git
    targetRevision: main
    path: .
  
  # Destination: EKS cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: mario
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
